# Generated by Django 2.0.3 on 2018-04-05 01:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='detailedAddress',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('선택 안 함', '선택 안 함'), ('여성', '여성'), ('남성', '남성')], default='N', max_length=10, verbose_name='성별(선택사항)'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=10, verbose_name='닉네임'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_nember',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+41524242424', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zipCode',
            field=models.PositiveIntegerField(null=True, verbose_name='우편주소'),
        ),
    ]
