# Generated by Django 2.0.3 on 2018-04-05 02:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20180405_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_nember',
            field=phonenumber_field.modelfields.PhoneNumberField(default='000-000-000', max_length=128, unique=True),
        ),
    ]
