# Generated by Django 2.0.3 on 2018-04-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20180405_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_nember',
            field=models.CharField(default='000-0000-0000', max_length=13),
        ),
    ]
