# Generated by Django 2.0.3 on 2018-04-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20180405_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_nember',
            field=models.CharField(default='', max_length=13),
        ),
    ]
