# Generated by Django 2.0.3 on 2018-04-06 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_items_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('아우터', (('셔츠', '셔츠'), ('가디건', '가디건'), ('코트', '코트'), ('점퍼', '점퍼'), ('패딩', '패딩'))), ('티셔츠', (('맨투맨', '맨투맨'), ('후드', '후드')))], default='', max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.AddField(
            model_name='items',
            name='Category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.Category'),
        ),
    ]
