# Generated by Django 2.0.3 on 2018-04-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180406_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_choices',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Category',
            new_name='category',
        ),
    ]
