# Generated by Django 2.0.3 on 2018-04-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180406_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='Item',
        ),
    ]
