# Generated by Django 2.0.3 on 2018-04-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180406_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_choices',
        ),
        migrations.AddField(
            model_name='category',
            name='c_name',
            field=models.CharField(default='', max_length=250, verbose_name='카테고리이름'),
        ),
        migrations.AddField(
            model_name='category',
            name='c_number',
            field=models.CharField(choices=[('O_01', (('Oj_0101', 'Oj_0101'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='', max_length=100, verbose_name='코드번호'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
