# Generated by Django 2.0.3 on 2018-04-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180406_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='c_number',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
