# Generated by Django 2.0.3 on 2018-04-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20180406_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='c_name',
        ),
        migrations.AddField(
            model_name='category',
            name='chop_category_name',
            field=models.CharField(blank=True, choices=[('아우터', (('셔츠', '셔츠'), ('가디건', '가디건'), ('코트', '코트'), ('점퍼', '점퍼'), ('패딩', '패딩'))), ('티셔츠', (('맨투맨', '맨투맨'), ('후드', '후드'), ('긴팔티/7부', '긴팔티/7부'), ('스트라이프', '스트라이프'), ('반팔', '반팔'), ('나시', '나시'))), ('셔츠', (('베이직/기본', '베이직/기본'), ('체크/패턴', '체크/패턴'), ('스프라이프', '스프라이프'), ('헨리넥/차이나', '헨라넥/차이나'), ('데님', '데님'))), ('니트/가디건', (('니트', '니트'), ('가디건', '가디건'), ('폴라&터틀', '폴라&터틀')))], default='', max_length=20, null=True, verbose_name='상품-카테고리이름'),
        ),
        migrations.AddField(
            model_name='category',
            name='notice_category_name',
            field=models.CharField(blank=True, choices=[('고객센터', (('공지사항', '공지사항'), ('문의게시판', '문의게시판'), ('상품리뷰', '상품리뷰')))], default='', max_length=20, null=True, verbose_name='게시판-카테고리이름'),
        ),
    ]
