# Generated by Django 2.0.3 on 2018-04-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20180406_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='notice_category_name',
        ),
    ]
