# Generated by Django 2.0.3 on 2018-04-06 06:32

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_remove_category_notice_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=djrichtextfield.models.RichTextField(default='', verbose_name='상품설명'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(default='', max_length=100, verbose_name='상품코드'),
        ),
        migrations.AddField(
            model_name='item',
            name='max_stock',
            field=models.PositiveIntegerField(default=1000, verbose_name='판매 재고(전체)'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.Category', verbose_name='카테고리'),
        ),
    ]
